version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres15:
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: temp123
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    image: redis:7.2.0
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning

networks:
  meilisearch:
    driver: bridge
